// This file is @generated by prost-build.
/// Frame represents a unified message structure for all communication
/// It contains all necessary metadata and the actual command
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Frame {
    /// The actual command
    #[prost(message, optional, tag = "1")]
    pub command: ::core::option::Option<super::flare_core_commands::Command>,
    /// Unique identifier for the message (used for acknowledgment and deduplication)
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    /// Reliability level of the message (best effort, at least once, exactly once, ordered)
    #[prost(enumeration = "Reliability", tag = "3")]
    pub reliability: i32,
    /// Timestamp when the message was created (milliseconds since Unix epoch)
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
    /// Optional session identifier for grouping related messages
    #[prost(string, optional, tag = "5")]
    pub session_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Message priority level (0-255, higher values indicate higher priority)
    #[prost(uint32, tag = "6")]
    pub priority: u32,
    /// Optional compression algorithm identifier (if payload is compressed)
    #[prost(uint32, optional, tag = "7")]
    pub compression: ::core::option::Option<u32>,
    /// Flag indicating whether the payload is encrypted
    #[prost(bool, tag = "8")]
    pub encrypted: bool,
    /// Metadata key-value pairs (for additional information like platform data)
    #[prost(map = "string, bytes", tag = "9")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::vec::Vec<u8>,
    >,
}
/// Reliability defines the delivery guarantees for messages
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Reliability {
    /// Best effort delivery (no guarantees)
    BestEffort = 0,
    /// At least once delivery (message may be duplicated but not lost)
    AtLeastOnce = 1,
    /// Exactly once delivery (message delivered exactly one time)
    ExactlyOnce = 2,
    /// Ordered delivery (messages delivered in order)
    Ordered = 3,
}
impl Reliability {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::BestEffort => "BEST_EFFORT",
            Self::AtLeastOnce => "AT_LEAST_ONCE",
            Self::ExactlyOnce => "EXACTLY_ONCE",
            Self::Ordered => "ORDERED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BEST_EFFORT" => Some(Self::BestEffort),
            "AT_LEAST_ONCE" => Some(Self::AtLeastOnce),
            "EXACTLY_ONCE" => Some(Self::ExactlyOnce),
            "ORDERED" => Some(Self::Ordered),
            _ => None,
        }
    }
}
