// This file is @generated by prost-build.
/// Command anvelope, wrapping specific commands
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Command {
    #[prost(oneof = "command::Command", tags = "1, 2, 3, 4, 5, 6")]
    pub command: ::core::option::Option<command::Command>,
}
/// Nested message and enum types in `Command`.
pub mod command {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "snake_case")]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Command {
        #[prost(message, tag = "1")]
        SendMessage(super::SendMessage),
        #[prost(message, tag = "2")]
        AckMessage(super::AckMessage),
        #[prost(message, tag = "3")]
        InitConnection(super::InitConnection),
        #[prost(message, tag = "4")]
        CloseConnection(super::CloseConnection),
        #[prost(message, tag = "5")]
        HeartbeatRequest(super::HeartbeatRequest),
        #[prost(message, tag = "6")]
        HeartbeatResponse(super::HeartbeatResponse),
    }
}
/// Command to send a message
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendMessage {
    #[prost(string, tag = "1")]
    pub topic: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub message_id: u64,
}
/// Acknowledgment for a message
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AckMessage {
    #[prost(uint64, tag = "1")]
    pub message_id: u64,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
/// Initialize a connection
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InitConnection {
    /// other handshake parameters
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
}
/// Close a connection
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseConnection {
    #[prost(int32, tag = "1")]
    pub reason_code: i32,
    #[prost(string, tag = "2")]
    pub reason_message: ::prost::alloc::string::String,
}
/// Heartbeat request
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeartbeatRequest {
    #[prost(uint64, tag = "1")]
    pub timestamp: u64,
}
/// Heartbeat response
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeartbeatResponse {
    #[prost(uint64, tag = "1")]
    pub timestamp: u64,
}
