// This file is @generated by prost-build.
/// Frame represents a unified message structure for all communication
/// It contains all necessary metadata and the actual payload
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Frame {
    /// Type of the message (e.g., heartbeat, data, control)
    #[prost(enumeration = "MessageType", tag = "1")]
    pub message_type: i32,
    /// Unique identifier for the message (used for acknowledgment and deduplication)
    #[prost(uint64, tag = "2")]
    pub message_id: u64,
    /// Reliability level of the message (best effort, at least once, exactly once, ordered)
    #[prost(enumeration = "Reliability", tag = "3")]
    pub reliability: i32,
    /// Timestamp when the message was created (milliseconds since Unix epoch)
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
    /// Actual message payload as bytes (can be serialized data of any format)
    #[prost(bytes = "vec", tag = "5")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// Optional session identifier for grouping related messages
    #[prost(string, optional, tag = "6")]
    pub session_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Message priority level (0-255, higher values indicate higher priority)
    #[prost(uint32, tag = "7")]
    pub priority: u32,
    /// Optional compression algorithm identifier (if payload is compressed)
    #[prost(uint32, optional, tag = "8")]
    pub compression: ::core::option::Option<u32>,
    /// Flag indicating whether the payload is encrypted
    #[prost(bool, tag = "9")]
    pub encrypted: bool,
}
/// MessageType defines all possible types of messages in the protocol
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    /// Unknown message type (should not be used in normal operation)
    Unknown = 0,
    /// Heartbeat messages for connection keep-alive
    Heartbeat = 1,
    HeartbeatAck = 2,
    /// Connection establishment and acknowledgment
    Connect = 3,
    ConnectAck = 4,
    /// Connection termination and acknowledgment
    Disconnect = 5,
    DisconnectAck = 6,
    /// Data transmission and acknowledgment
    Data = 7,
    DataAck = 8,
    /// Retransmission of previously sent data
    Retransmit = 9,
    /// Protocol switching control messages
    ProtocolSwitch = 10,
    /// Protocol testing messages
    ProtocolTest = 11,
    /// Error reporting messages
    Error = 12,
    /// Notification messages
    Notification = 13,
    /// Custom event messages (application-defined)
    CustomEvent = 17,
    /// Custom message types (application-defined)
    CustomMessage = 18,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Heartbeat => "HEARTBEAT",
            Self::HeartbeatAck => "HEARTBEAT_ACK",
            Self::Connect => "CONNECT",
            Self::ConnectAck => "CONNECT_ACK",
            Self::Disconnect => "DISCONNECT",
            Self::DisconnectAck => "DISCONNECT_ACK",
            Self::Data => "DATA",
            Self::DataAck => "DATA_ACK",
            Self::Retransmit => "RETRANSMIT",
            Self::ProtocolSwitch => "PROTOCOL_SWITCH",
            Self::ProtocolTest => "PROTOCOL_TEST",
            Self::Error => "ERROR",
            Self::Notification => "NOTIFICATION",
            Self::CustomEvent => "CUSTOM_EVENT",
            Self::CustomMessage => "CUSTOM_MESSAGE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "HEARTBEAT" => Some(Self::Heartbeat),
            "HEARTBEAT_ACK" => Some(Self::HeartbeatAck),
            "CONNECT" => Some(Self::Connect),
            "CONNECT_ACK" => Some(Self::ConnectAck),
            "DISCONNECT" => Some(Self::Disconnect),
            "DISCONNECT_ACK" => Some(Self::DisconnectAck),
            "DATA" => Some(Self::Data),
            "DATA_ACK" => Some(Self::DataAck),
            "RETRANSMIT" => Some(Self::Retransmit),
            "PROTOCOL_SWITCH" => Some(Self::ProtocolSwitch),
            "PROTOCOL_TEST" => Some(Self::ProtocolTest),
            "ERROR" => Some(Self::Error),
            "NOTIFICATION" => Some(Self::Notification),
            "CUSTOM_EVENT" => Some(Self::CustomEvent),
            "CUSTOM_MESSAGE" => Some(Self::CustomMessage),
            _ => None,
        }
    }
}
/// Reliability defines the delivery guarantees for messages
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Reliability {
    /// Best effort delivery (no guarantees)
    BestEffort = 0,
    /// At least once delivery (message may be duplicated but not lost)
    AtLeastOnce = 1,
    /// Exactly once delivery (message delivered exactly one time)
    ExactlyOnce = 2,
    /// Ordered delivery (messages delivered in order)
    Ordered = 3,
}
impl Reliability {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::BestEffort => "BEST_EFFORT",
            Self::AtLeastOnce => "AT_LEAST_ONCE",
            Self::ExactlyOnce => "EXACTLY_ONCE",
            Self::Ordered => "ORDERED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BEST_EFFORT" => Some(Self::BestEffort),
            "AT_LEAST_ONCE" => Some(Self::AtLeastOnce),
            "EXACTLY_ONCE" => Some(Self::ExactlyOnce),
            "ORDERED" => Some(Self::Ordered),
            _ => None,
        }
    }
}
