// This file is @generated by prost-build.
/// 长链接大类命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Command {
    #[prost(oneof = "command::CommandType", tags = "1, 2, 3, 4")]
    pub command_type: ::core::option::Option<command::CommandType>,
}
/// Nested message and enum types in `Command`.
pub mod command {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "snake_case")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum CommandType {
        #[prost(message, tag = "1")]
        Control(super::ControlCmd),
        #[prost(message, tag = "2")]
        Message(super::MessageCmd),
        #[prost(message, tag = "3")]
        Notification(super::NotificationCmd),
        #[prost(message, tag = "4")]
        Event(super::EventCmd),
    }
}
/// 控制类子命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ControlCmd {
    #[prost(oneof = "control_cmd::ControlType", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub control_type: ::core::option::Option<control_cmd::ControlType>,
}
/// Nested message and enum types in `ControlCmd`.
pub mod control_cmd {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "snake_case")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ControlType {
        #[prost(message, tag = "1")]
        Connect(super::ConnectCommand),
        #[prost(message, tag = "2")]
        ConnectAck(super::ConnectAckCommand),
        #[prost(message, tag = "3")]
        Disconnect(super::DisconnectCommand),
        #[prost(message, tag = "4")]
        AuthRequest(super::AuthRequestCommand),
        #[prost(message, tag = "5")]
        AuthResponse(super::AuthResponseCommand),
        #[prost(message, tag = "6")]
        Ping(super::PingCommand),
        #[prost(message, tag = "7")]
        Pong(super::PongCommand),
        #[prost(message, tag = "8")]
        Error(super::ErrorCommand),
        #[prost(message, tag = "9")]
        Custom(super::CustomCommand),
    }
}
/// 消息类子命令（需要ACK确认）
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageCmd {
    #[prost(oneof = "message_cmd::MessageType", tags = "1, 2, 3, 4")]
    pub message_type: ::core::option::Option<message_cmd::MessageType>,
}
/// Nested message and enum types in `MessageCmd`.
pub mod message_cmd {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "snake_case")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum MessageType {
        #[prost(message, tag = "1")]
        Send(super::MessageSendCommand),
        #[prost(message, tag = "2")]
        Ack(super::MessageAckCommand),
        #[prost(message, tag = "3")]
        Data(super::DataCommand),
        #[prost(message, tag = "4")]
        Custom(super::CustomCommand),
    }
}
/// 通知类子命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotificationCmd {
    #[prost(oneof = "notification_cmd::NotificationType", tags = "1, 2, 3, 4")]
    pub notification_type: ::core::option::Option<notification_cmd::NotificationType>,
}
/// Nested message and enum types in `NotificationCmd`.
pub mod notification_cmd {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "snake_case")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum NotificationType {
        #[prost(message, tag = "1")]
        System(super::NotificationCommand),
        #[prost(message, tag = "2")]
        Broadcast(super::NotificationCommand),
        #[prost(message, tag = "3")]
        Alert(super::NotificationCommand),
        #[prost(message, tag = "4")]
        Custom(super::CustomCommand),
    }
}
/// 事件类子命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventCmd {
    #[prost(oneof = "event_cmd::EventType", tags = "1, 2, 3, 4")]
    pub event_type: ::core::option::Option<event_cmd::EventType>,
}
/// Nested message and enum types in `EventCmd`.
pub mod event_cmd {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "snake_case")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum EventType {
        #[prost(message, tag = "1")]
        Open(super::OpenCommand),
        #[prost(message, tag = "2")]
        Close(super::CloseCommand),
        #[prost(message, tag = "3")]
        Reconnect(super::ReconnectCommand),
        #[prost(message, tag = "4")]
        Custom(super::CustomCommand),
    }
}
/// 自定义命令结构
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CustomCommand {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(map = "string, string", tag = "3")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// 连接命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectCommand {
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub platform: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub version: ::prost::alloc::string::String,
}
/// 连接确认命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectAckCommand {
    #[prost(int32, tag = "1")]
    pub status: i32,
    #[prost(string, tag = "2")]
    pub status_message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub session_id: ::prost::alloc::string::String,
}
/// 断开连接命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisconnectCommand {
    #[prost(int32, tag = "1")]
    pub status: i32,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub details: ::prost::alloc::string::String,
}
/// 认证请求命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthRequestCommand {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub platform: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub token: ::prost::alloc::string::String,
}
/// 认证响应命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthResponseCommand {
    #[prost(int32, tag = "1")]
    pub status: i32,
    #[prost(string, tag = "2")]
    pub status_message: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub success: bool,
    #[prost(bytes = "vec", tag = "4")]
    pub user_info: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "5")]
    pub error_message: ::prost::alloc::string::String,
}
/// 消息发送命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSendCommand {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// 消息确认命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageAckCommand {
    #[prost(int32, tag = "1")]
    pub status: i32,
    #[prost(string, tag = "2")]
    pub status_message: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub success: bool,
    #[prost(string, tag = "4")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub error_code: u32,
    #[prost(string, tag = "6")]
    pub error_message: ::prost::alloc::string::String,
}
/// 数据命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataCommand {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// 通知命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotificationCommand {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub notification_type: ::prost::alloc::string::String,
}
/// 错误命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorCommand {
    #[prost(int32, tag = "1")]
    pub status: i32,
    #[prost(uint32, tag = "2")]
    pub code: u32,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub details: ::prost::alloc::string::String,
}
/// 事件命令
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PingCommand {}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PongCommand {}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OpenCommand {}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CloseCommand {}
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReconnectCommand {}
