// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Frame {
    #[prost(enumeration = "MessageType", tag = "1")]
    pub message_type: i32,
    #[prost(uint64, tag = "2")]
    pub message_id: u64,
    #[prost(enumeration = "Reliability", tag = "3")]
    pub reliability: i32,
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
    #[prost(bytes = "vec", tag = "5")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag = "6")]
    pub session_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, tag = "7")]
    pub priority: u32,
    #[prost(uint32, optional, tag = "8")]
    pub compression: ::core::option::Option<u32>,
    #[prost(bool, tag = "9")]
    pub encrypted: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    Unknown = 0,
    Heartbeat = 1,
    HeartbeatAck = 2,
    Connect = 3,
    ConnectAck = 4,
    Disconnect = 5,
    DisconnectAck = 6,
    Data = 7,
    DataAck = 8,
    Retransmit = 9,
    ProtocolSwitch = 10,
    ProtocolTest = 11,
    Error = 12,
    Notification = 13,
    CustomEvent = 17,
    CustomMessage = 18,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Heartbeat => "HEARTBEAT",
            Self::HeartbeatAck => "HEARTBEAT_ACK",
            Self::Connect => "CONNECT",
            Self::ConnectAck => "CONNECT_ACK",
            Self::Disconnect => "DISCONNECT",
            Self::DisconnectAck => "DISCONNECT_ACK",
            Self::Data => "DATA",
            Self::DataAck => "DATA_ACK",
            Self::Retransmit => "RETRANSMIT",
            Self::ProtocolSwitch => "PROTOCOL_SWITCH",
            Self::ProtocolTest => "PROTOCOL_TEST",
            Self::Error => "ERROR",
            Self::Notification => "NOTIFICATION",
            Self::CustomEvent => "CUSTOM_EVENT",
            Self::CustomMessage => "CUSTOM_MESSAGE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "HEARTBEAT" => Some(Self::Heartbeat),
            "HEARTBEAT_ACK" => Some(Self::HeartbeatAck),
            "CONNECT" => Some(Self::Connect),
            "CONNECT_ACK" => Some(Self::ConnectAck),
            "DISCONNECT" => Some(Self::Disconnect),
            "DISCONNECT_ACK" => Some(Self::DisconnectAck),
            "DATA" => Some(Self::Data),
            "DATA_ACK" => Some(Self::DataAck),
            "RETRANSMIT" => Some(Self::Retransmit),
            "PROTOCOL_SWITCH" => Some(Self::ProtocolSwitch),
            "PROTOCOL_TEST" => Some(Self::ProtocolTest),
            "ERROR" => Some(Self::Error),
            "NOTIFICATION" => Some(Self::Notification),
            "CUSTOM_EVENT" => Some(Self::CustomEvent),
            "CUSTOM_MESSAGE" => Some(Self::CustomMessage),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Reliability {
    BestEffort = 0,
    AtLeastOnce = 1,
    ExactlyOnce = 2,
    Ordered = 3,
}
impl Reliability {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::BestEffort => "BEST_EFFORT",
            Self::AtLeastOnce => "AT_LEAST_ONCE",
            Self::ExactlyOnce => "EXACTLY_ONCE",
            Self::Ordered => "ORDERED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BEST_EFFORT" => Some(Self::BestEffort),
            "AT_LEAST_ONCE" => Some(Self::AtLeastOnce),
            "EXACTLY_ONCE" => Some(Self::ExactlyOnce),
            "ORDERED" => Some(Self::Ordered),
            _ => None,
        }
    }
}
